% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Homework \#02: Data Wrangling and Joins}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{due {[}date{]} 11:59 PM}
\author{Dav King}
\date{1/28/22}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Homework \#02: Data Wrangling and Joins},
  pdfauthor={Dav King},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{load-packages-and-data}{%
\section{Load Packages and Data}\label{load-packages-and-data}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(viridis)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{natunivs }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"NatUnivs.csv"}\NormalTok{)}
\NormalTok{slacs }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"SLACs.csv"}\NormalTok{)}
\NormalTok{presvote\_pop }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"PresVote\_Population.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{exercise-1}{%
\section{Exercise 1}\label{exercise-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\OtherTok{\textless{}{-}}\NormalTok{ natunivs }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{full\_join}\NormalTok{(slacs, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"school"}\NormalTok{, }\StringTok{"state"}\NormalTok{,}
                             \StringTok{"rank\_2022"}\NormalTok{, }\StringTok{"rank\_2021"}\NormalTok{, }\StringTok{"natuniv\_slac"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{inner\_join}\NormalTok{(presvote\_pop, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"state"} \OtherTok{=} \StringTok{"abbrev"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{exercise-2}{%
\section{Exercise 2}\label{exercise-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(state) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{nSchools =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(nSchools)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(state)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 1
##   state
##   <chr>
## 1 CA   
## 2 MA   
## 3 NY   
## 4 PA   
## 5 OH
\end{verbatim}

The 5 states which have the most schools in the \texttt{full\_data} data
set are California, Massachusetts, New York, Pennsylvania, and Ohio,
respectively.

\hypertarget{exercise-3}{%
\section{Exercise 3}\label{exercise-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{presvote\_pop }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{anti\_join}\NormalTok{(full\_data, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"abbrev"} \OtherTok{=} \StringTok{"state"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{2020pop}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\StringTok{"abbrev"}\NormalTok{, }\StringTok{"2020pop"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 20 x 2
##    abbrev `2020pop`
##    <chr>      <dbl>
##  1 AZ       7151502
##  2 AL       5024279
##  3 OR       4237256
##  4 OK       3959353
##  5 UT       3271616
##  6 NV       3104614
##  7 AR       3011524
##  8 MS       2961279
##  9 KS       2937880
## 10 NM       2117522
## 11 NE       1961504
## 12 ID       1839106
## 13 WV       1793716
## 14 HI       1455271
## 15 MT       1084225
## 16 DE        989948
## 17 SD        886667
## 18 ND        779094
## 19 AK        733391
## 20 WY        576851
\end{verbatim}

The state with the largest population that does not have a school in
\texttt{full\_data} is Arizona.

\hypertarget{exercise-4}{%
\section{Exercise 4}\label{exercise-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{winner =} \FunctionTok{if\_else}\NormalTok{(bidenvotes }\SpecialCharTok{\textgreater{}}\NormalTok{ trumpvotes, }\StringTok{"Biden"}\NormalTok{, }\StringTok{"Trump"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(., }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ winner, }\AttributeTok{fill =}\NormalTok{ natuniv\_slac)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Political Leanings of States with Top Ranked Schools"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Who won in 2020?"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Number of Schools"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Type of Institution"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_viridis}\NormalTok{(}\AttributeTok{discrete =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{option =} \StringTok{"D"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw02-template_files/figure-latex/copy_plot-1.pdf}

In general, the states that Biden won contained far more top ranked
schools (over 80) than the states Trump won (roughly 25). In general,
the proportion overall seems to be about 50/50 between National Liberal
Arts Colleges and National Universities, with no notable difference in
their distribution in Trump versus Biden states.

\hypertarget{exercise-5}{%
\section{Exercise 5}\label{exercise-5}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{counts }\OtherTok{\textless{}{-}}\NormalTok{ full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(state) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{())}
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{full\_join}\NormalTok{(}\AttributeTok{y=}\NormalTok{counts, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"school"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(., }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{\textasciigrave{}}\AttributeTok{2020pop.x}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{y =}\NormalTok{ count)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =}\NormalTok{ lm) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Population of US States and Number of Top{-}Ranked Schools"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"2020 Population"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Number of Top Ranked Schools"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw02-template_files/figure-latex/school_pop_plot-1.pdf}
This graph, using a linear regression line, shows a clear positive
relationship between 2020 population and number of top ranked schools in
a state. However, this appears to be something of an overplotting error.
The data are not very linearly distributed, and the linear regression
line owes most of its strength to a few outliers than it does a true
underlying data structure (which there may well be in a relationship
with a discrete variable like a number of schools). Consider, for
example, the graph below - fitted with a Loess regression line instead
of a linear one. It suggests that the relationship is almost cubic -
certainly, not a standard linear relationship.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{full\_join}\NormalTok{(}\AttributeTok{y=}\NormalTok{counts, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"school"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(., }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{\textasciigrave{}}\AttributeTok{2020pop.x}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{y =}\NormalTok{ count)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =}\NormalTok{ loess) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Population of US States and Number of Top{-}Ranked Schools"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"With Loess Regression Line"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"2020 Population"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Number of Top Ranked Schools"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{hw02-template_files/figure-latex/loess_graph-1.pdf}

\hypertarget{exercise-6}{%
\section{Exercise 6}\label{exercise-6}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(state }\SpecialCharTok{==} \StringTok{"NC"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(school) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{rank\_diff =}\NormalTok{ rank\_2021 }\SpecialCharTok{{-}}\NormalTok{ rank\_2022) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(school, rank\_diff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
## # Groups:   school [4]
##   school                                   rank_diff
##   <chr>                                        <dbl>
## 1 Duke University                                  3
## 2 University of North Carolina-Chapel Hill         0
## 3 Wake Forest University                           0
## 4 Davidson College                                 2
\end{verbatim}

There are four schools in North Carolina in this dataset of top schools
- Duke University, Davidson College, Wake Forest University, and our
neighbors eight miles down the road. The ``University'' of North
Carolina and Wake Forest did not change their rankings from 2021 to
2022, while Davidson improved 2 places and Duke increased by 3 (the Duke
Difference).

\hypertarget{exercise-7}{%
\section{Exercise 7}\label{exercise-7}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{biden\_share =}\NormalTok{ bidenvotes }\SpecialCharTok{/}\NormalTok{ (bidenvotes }\SpecialCharTok{+}\NormalTok{ trumpvotes)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(natuniv\_slac) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{mean\_Biden =} \FunctionTok{mean}\NormalTok{(biden\_share), }\AttributeTok{mean\_pop =} \FunctionTok{mean}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{2020pop}\StringTok{\textasciigrave{}}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   natuniv_slac                  mean_Biden  mean_pop
##   <chr>                              <dbl>     <dbl>
## 1 National Liberal Arts College      0.563 14018730.
## 2 National University                0.572 16101703.
\end{verbatim}

There seem to be no real differences in Biden vote share between the two
groups of colleges - 56.3\% of the vote in one and 57.2\% of the vote in
the other. However, there is a notable difference in how populous th
states containing the two types of schools are. States with National
Liberal Arts Colleges tend to average around 14 million people, while
states with National Universities tend to average around 16 million.

\end{document}
